---
parent_config: config/ig_bg_common.yml

dataset:
  root_dir: data/Pomaria_0_int_home_office_0/
  scene_info_path: scene/00000/
  img_wh: [640, 480]
  # img_wh: [320, 240]
  scene_center: [-6.5, -1.0, 1.3]
