---
parent_config: config/ig_bg_common.yml

dataset:
  root_dir: data/Merom_1_int_childs_room_0/
  scene_info_path: scene/00000/
  img_wh: [640, 480]
  # img_wh: [320, 240]
  scene_center: [-0.7, 0.0, 1.3]