---
parent_config: config/ig_bg_common.yml

dataset:
  root_dir: data/Rs_int_living_room_0_view_50/
  scene_info_path: scene/00000/
  # img_wh: [640, 480]
  img_wh: [320, 240]
  scene_center: [0, -1.5, 1.3]
